modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Botany-Pots-Pixelmon/issues"
license="LGPL v2.1"

[[mods]]
modId="botanypotspixelmon"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.botanypotspixelmon]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanypotspixelmon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.botanypotspixelmon]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.botanypotspixelmon]]
    modId="botanypots"
    mandatory=true
    versionRange="[6,)"
    ordering="AFTER"
    side="BOTH"